name: Deploy to BentoCloud

on:
  push:
    branches:
      - main
    paths:
      - 'service.py'
      - 'deployment.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      BENTOML_VERSION: ${{ secrets.BENTOML_VERSION }}
      SUMMARY_TEXT: ${{ secrets.SUMMARY_TEXT }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -z "$BENTOML_VERSION" ]; then
            pip install bentoml
          else
            pip install "bentoml==$BENTOML_VERSION"
          fi
          
      - name: Log in to BentoCloud
        run: |
          echo "Log in to BentoCloud at ${{ secrets.BENTOCLOUD_ENDPOINT }}"
          bentoml cloud login --api-token ${{ secrets.BENTOCLOUD_API_TOKEN }} --endpoint ${{ secrets.BENTOCLOUD_ENDPOINT }}

      - name: Check for file changes
        id: check_changes
        run: |
          # Check if service.py has changed
          git diff --name-only HEAD^ HEAD | grep -q "service.py" && echo "service_changed=true" >> $GITHUB_ENV || echo "service_changed=false" >> $GITHUB_ENV
          
          # Check if deployment.yaml has changed
          git diff --name-only HEAD^ HEAD | grep -q "deployment.yaml" && echo "deployment_changed=true" >> $GITHUB_ENV || echo "deployment_changed=false" >> $GITHUB_ENV

      - name: Update BentoML Service on BentoCloud
        if: env.service_changed == 'true'
        run: |
          bentoml deployment update ${{ secrets.DEPLOYMENT_NAME }} --bento .
          
      - name: Update Deployment Configs on BentoCloud (if deployment.yaml changed)
        if: env.deployment_changed == 'true'
        run: |
          bentoml deployment update -f deployment.yaml
          
      - name: Run Test Inference
        run: |
          # Wait for deployment to be ready
          sleep 30
          curl -X POST "${{ secrets.DEPLOYMENT_URL }}/summarize" \
            -H "accept: text/plain" \
            -H "Content-Type: application/json" \
            -d "{\"text\": \"${{ env.SUMMARY_TEXT }}\"}"
