name: Deploy to BentoCloud

on:
  push:
    branches:
      - main
    paths:
      - 'service.py'
      - 'deployment.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      BENTOML_VERSION: ${{ secrets.BENTOML_VERSION }}
      SUMMARY_TEXT: ${{ secrets.SUMMARY_TEXT }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Ensure enough commit history for diffing

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -z "$BENTOML_VERSION" ]; then
            pip install bentoml
          else
            pip install "bentoml==$BENTOML_VERSION"
          fi

      - name: Log in to BentoCloud
        run: |
          echo "Log in to BentoCloud at ${{ secrets.BENTOCLOUD_ENDPOINT }}"
          bentoml cloud login --api-token ${{ secrets.BENTOCLOUD_API_TOKEN }} --endpoint ${{ secrets.BENTOCLOUD_ENDPOINT }}

      - name: Check for file changes
        id: check_changes
        run: |
          git fetch origin main --depth=2
          changed_files=$(git diff --name-only origin/main~1..origin/main)

          echo "Changed files: $changed_files"

          if echo "$changed_files" | grep -q "service.py"; then
            echo "service_changed=true" >> $GITHUB_ENV
          else
            echo "service_changed=false" >> $GITHUB_ENV
          fi

          if echo "$changed_files" | grep -q "deployment.yaml"; then
            echo "deployment_changed=true" >> $GITHUB_ENV
          else
            echo "deployment_changed=false" >> $GITHUB_ENV
          fi

      - name: Update BentoML Service on BentoCloud
        if: env.service_changed == 'true'
        run: |
          bentoml deployment update ${{ secrets.DEPLOYMENT_NAME }} --bento .

      - name: Update Deployment Configs on BentoCloud (if deployment.yaml changed)
        if: env.deployment_changed == 'true'
        run: |
          bentoml deployment update ${{ secrets.DEPLOYMENT_NAME }} -f deployment.yaml

      - name: Run Test Inference
        run: |
          # Wait for deployment to be ready
          sleep 30
          curl -X POST "${{ secrets.DEPLOYMENT_URL }}/summarize" \
            -H "accept: text/plain" \
            -H "Content-Type: application/json" \
            -d "{\"text\": \"${{ env.SUMMARY_TEXT }}\"}"
