name: Update Code

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'deployment.yaml'

jobs:
  update-code:
    runs-on: ubuntu-latest

    env:
      BENTOML_VERSION: ${{ secrets.BENTOML_VERSION }}
      SUMMARY_TEXT: ${{ secrets.SUMMARY_TEXT }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install BentoML
        run: |
          python -m pip install --upgrade pip
          if [ -z "$BENTOML_VERSION" ]; then
            pip install bentoml
          else
            pip install "bentoml==$BENTOML_VERSION"
          fi
          pip install huggingface_hub

      - name: Log in to BentoCloud
        run: |
          echo "Logging in to BentoCloud"
          bentoml cloud login --api-token ${{ secrets.BENTOCLOUD_API_TOKEN }} --endpoint ${{ secrets.BENTOCLOUD_ENDPOINT }}

      - name: Update BentoML Service
        run: |
          bentoml deployment update ${{ secrets.DEPLOYMENT_NAME }} --bento .

      - name: Deploy and Run Test Inference
	shell: python
	run: |
	  import bentoml
 
          deployment = bentoml.deployment.update(
	       name="${{ secrets.DEPLOYMENT_NAME }}",
	       bento=".",
	  )
			
	  # Wait until the deployment is live (or timeout after 60 seconds)
	  code = deployment.wait_until_ready(timeout=60)
			
	  if code != 0:
	      raise RuntimeError("Deployment did not become ready in time.")
			
	  client = deployment.get_client()
	  response = client.summarize(text="This is a sample prompt for testing.")
	  print(response)
