name: Update Service Code or Other Files

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'deployment.yaml'

jobs:
  update-service:
    runs-on: ubuntu-latest

    env:
      BENTOML_VERSION: ${{ secrets.BENTOML_VERSION }}
      SUMMARY_TEXT: ${{ secrets.SUMMARY_TEXT }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install BentoML
        run: |
          python -m pip install --upgrade pip
          if [ -z "$BENTOML_VERSION" ]; then
            pip install bentoml
          else
            pip install "bentoml==$BENTOML_VERSION"
          fi
          pip install huggingface_hub

      - name: Log in to BentoCloud
        run: |
          echo "Logging into BentoCloud"
          bentoml cloud login --api-token ${{ secrets.BENTOCLOUD_API_TOKEN }} --endpoint ${{ secrets.BENTOCLOUD_ENDPOINT }}

      - name: Update BentoML Service
        run: |
          bentoml deployment update ${{ secrets.DEPLOYMENT_NAME }} --bento .

      - name: Run Test Inference with Readiness Check
        run: |
          python3 <<EOF
          import time
          import bentoml
      
          client = bentoml.SyncHTTPClient("${{ secrets.DEPLOYMENT_URL }}")
      
          for _ in range(10):  # Try for up to ~30 seconds
              if client.is_ready():
                  break
              time.sleep(3)
          else:
              raise RuntimeError("Service is not ready after 30 seconds.")
      
          response = client.summarize(text="${{ env.SUMMARY_TEXT }}")
          print(response)
          EOF
