name: Update Deployment Config

on:
  push:
    branches:
      - main
    paths:
      - 'deployment.yaml'

jobs:
  update-deployment:
    runs-on: ubuntu-latest

    env:
      BENTOML_VERSION: ${{ secrets.BENTOML_VERSION }}
      SUMMARY_TEXT: ${{ secrets.SUMMARY_TEXT }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install BentoML
        run: |
          python -m pip install --upgrade pip
          if [ -z "$BENTOML_VERSION" ]; then
            pip install bentoml
          else
            pip install "bentoml==$BENTOML_VERSION"
          fi

      - name: Log in to BentoCloud
        run: |
          echo "Logging into BentoCloud"
          bentoml cloud login --api-token ${{ secrets.BENTOCLOUD_API_TOKEN }} --endpoint ${{ secrets.BENTOCLOUD_ENDPOINT }}

      - name: Update Deployment Config
        run: |
          bentoml deployment update -f deployment.yaml

      - name: Run Test Inference
        run: |
          # Wait for deployment to be ready
          sleep 30
          curl -X POST "${{ secrets.DEPLOYMENT_URL }}/summarize" \
            -H "accept: text/plain" \
            -H "Content-Type: application/json" \
            -d "{\"text\": \"${{ env.SUMMARY_TEXT }}\"}"
